### ISSUE TITLE
Отсутствие username 'а

### ISSUE THREAD

**Issue by Lesnik19** [Justiks228/ChessBot#6]
При отсутствии  username 'а, бот агрится на тебя.
![Screenshot_20240616-140047](https://github.com/Justiks1337/ChessBot/assets/155076006/cedebd5f-5dc3-48fd-9d00-9f5c137f8b13)
![Screenshot_20240616-140309](https://github.com/Justiks1337/ChessBot/assets/155076006/532cb33d-5604-4c64-988d-3799d66413b3)

**Comment by Justiks1337** [comment]
https://github.com/Justiks1337/ChessBot/commit/53f8235d08d4bf73fb2426e267d855a28d1ee0d4
